/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class HookJs {
  stop(): void
  get isRunning(): boolean
  /**
   * Update the event filter bitmask at runtime without restarting the hook.
   * Each bit corresponds to an EventTypeJs value (bit 0 = HookEnabled, bit 2 = KeyPressed, etc.).
   * Set to 0x7FF (2047) for all events, or combine specific bits.
   */
  setEventMask(mask: number): void
  /** Get the current event filter bitmask. */
  get eventMask(): number
}

/**
 * EventEmitter-style input hook with per-event-type callbacks.
 *
 * Unlike `startListen()` which sends all events through a single callback,
 * `InputHook` dispatches events to typed callbacks registered via `onKeyDown()`,
 * `onMouseMove()`, etc. Only registered event types cross the NAPI boundary —
 * the event mask is computed automatically from which callbacks are set.
 *
 * ```js
 * const hook = new InputHook();
 * hook.onKeyDown((data) => console.log("key:", data.key, data.rawCode));
 * hook.onMouseMove((data) => console.log("mouse:", data.x, data.y));
 * hook.start();
 * // ... later:
 * hook.stop();
 * ```
 */
export declare class InputHook {
  constructor()
  onKeyDown(callback: (data: KeyboardEventJs) => void): void
  onKeyUp(callback: (data: KeyboardEventJs) => void): void
  onMouseDown(callback: (data: MouseButtonEventJs) => void): void
  onMouseUp(callback: (data: MouseButtonEventJs) => void): void
  onClick(callback: (data: MouseButtonEventJs) => void): void
  onMouseMove(callback: (data: MouseMoveEventJs) => void): void
  onWheel(callback: (data: WheelEventJs) => void): void
  offKeyDown(): void
  offKeyUp(): void
  offMouseDown(): void
  offMouseUp(): void
  offClick(): void
  offMouseMove(): void
  offWheel(): void
  removeAllListeners(): void
  start(): void
  stop(): void
  get isRunning(): boolean
  get eventMask(): number
}

export declare enum ButtonJs {
  Left = 0,
  Right = 1,
  Middle = 2,
  Button4 = 3,
  Button5 = 4,
  Unknown = 5,
}

/**
 * Compute an event mask from a list of subscription pattern strings.
 *
 * Recognized patterns:
 * - `"keyboard:*"` or any `"keyboard:..."` → keyboard events
 * - `"mouse:down"`, `"mouse:up"`, `"mouse:click"` → mouse button events
 * - `"mouse:move"` → mouse movement events
 * - `"mouse:scroll"` → mouse wheel events
 * - `"mouse:*"` or other `"mouse:..."` → all mouse events
 *
 * Returns `EVENT_MASK_ALL` if no patterns match (safe default).
 */
export declare function computeEventMask(patterns: Array<string>): number

export interface DisplayInfoJs {
  id: number
  bounds: RectJs
  scaleFactor: number
  refreshRate?: number
  isPrimary: boolean
}

/**
 * Predefined event masks for common subscription patterns.
 * Use these with `startListen`'s `eventMask` parameter or `HookJs.setEventMask()`.
 *
 * - `EVENT_MASK_ALL` (0x7FF): All events
 * - `EVENT_MASK_KEYBOARD` (0x1C): KeyPressed | KeyReleased | KeyTyped
 * - `EVENT_MASK_MOUSE_BUTTONS` (0xE0): MousePressed | MouseReleased | MouseClicked
 * - `EVENT_MASK_MOUSE_MOVEMENT` (0x300): MouseMoved | MouseDragged
 * - `EVENT_MASK_MOUSE_WHEEL` (0x400): MouseWheel
 * - `EVENT_MASK_MOUSE_ALL` (0x7E0): All mouse events
 */
export const EVENT_MASK_ALL: number

export const EVENT_MASK_KEYBOARD: number

export const EVENT_MASK_MOUSE_ALL: number

export const EVENT_MASK_MOUSE_BUTTONS: number

export const EVENT_MASK_MOUSE_MOVEMENT: number

export const EVENT_MASK_MOUSE_WHEEL: number

export interface EventJs {
  eventType: EventTypeJs
  time: number
  keyboard?: KeyboardDataJs
  mouse?: MouseDataJs
  wheel?: WheelDataJs
}

export declare enum EventTypeJs {
  HookEnabled = 0,
  HookDisabled = 1,
  KeyPressed = 2,
  KeyReleased = 3,
  KeyTyped = 4,
  MousePressed = 5,
  MouseReleased = 6,
  MouseClicked = 7,
  MouseMoved = 8,
  MouseDragged = 9,
  MouseWheel = 10,
}

/** Get display info for all known keys. */
export declare function getAllKeyDisplayInfo(): Array<KeyDisplayInfo>

/** Get the display name for a mouse button. */
export declare function getButtonDisplayName(button: ButtonJs): string

/** Get display at a specific point */
export declare function getDisplayAtPoint(x: number, y: number): DisplayInfoJs | null

/** Get all displays */
export declare function getDisplays(): Array<DisplayInfoJs>

/** Get the category for a key (e.g. "letter", "modifier", "arrow", "function"). */
export declare function getKeyCategory(key: KeyJs): string

/** Get the display name for a key. */
export declare function getKeyDisplayName(key: KeyJs): string

/** Get the current mouse cursor position */
export declare function getMousePosition(): MouseDataJs

/** Get the primary display */
export declare function getPrimaryDisplay(): DisplayInfoJs

/** Get system settings */
export declare function getSystemSettings(): SystemSettingsJs

/** Check whether a subscription pattern is input-related (keyboard or mouse). */
export declare function isInputPattern(pattern: string): boolean

/** Check if a key is a modifier key. */
export declare function isModifierKey(key: KeyJs): boolean

export interface KeyboardDataJs {
  key: KeyJs
  rawCode: number
}

/** Keyboard event payload for onKeyDown / onKeyUp callbacks. */
export interface KeyboardEventJs {
  key: KeyJs
  rawCode: number
  time: number
}

export interface KeyDisplayInfo {
  key: number
  displayName: string
  category: string
}

export declare enum KeyJs {
  KeyA = 0,
  KeyB = 1,
  KeyC = 2,
  KeyD = 3,
  KeyE = 4,
  KeyF = 5,
  KeyG = 6,
  KeyH = 7,
  KeyI = 8,
  KeyJ = 9,
  KeyK = 10,
  KeyL = 11,
  KeyM = 12,
  KeyN = 13,
  KeyO = 14,
  KeyP = 15,
  KeyQ = 16,
  KeyR = 17,
  KeyS = 18,
  KeyT = 19,
  KeyU = 20,
  KeyV = 21,
  KeyW = 22,
  KeyX = 23,
  KeyY = 24,
  KeyZ = 25,
  Num0 = 26,
  Num1 = 27,
  Num2 = 28,
  Num3 = 29,
  Num4 = 30,
  Num5 = 31,
  Num6 = 32,
  Num7 = 33,
  Num8 = 34,
  Num9 = 35,
  F1 = 36,
  F2 = 37,
  F3 = 38,
  F4 = 39,
  F5 = 40,
  F6 = 41,
  F7 = 42,
  F8 = 43,
  F9 = 44,
  F10 = 45,
  F11 = 46,
  F12 = 47,
  Escape = 48,
  Space = 49,
  Enter = 50,
  Backspace = 51,
  Tab = 52,
  ShiftLeft = 53,
  ShiftRight = 54,
  ControlLeft = 55,
  ControlRight = 56,
  AltLeft = 57,
  AltRight = 58,
  MetaLeft = 59,
  MetaRight = 60,
  CapsLock = 61,
  Delete = 62,
  ArrowLeft = 63,
  ArrowRight = 64,
  ArrowUp = 65,
  ArrowDown = 66,
  Unknown = 67,
  Insert = 68,
  Home = 69,
  End = 70,
  PageUp = 71,
  PageDown = 72,
  NumLock = 73,
  ScrollLock = 74,
  PrintScreen = 75,
  Pause = 76,
  Grave = 77,
  Minus = 78,
  Equal = 79,
  BracketLeft = 80,
  BracketRight = 81,
  Backslash = 82,
  Semicolon = 83,
  Quote = 84,
  Comma = 85,
  Period = 86,
  Slash = 87,
  F13 = 88,
  F14 = 89,
  F15 = 90,
  F16 = 91,
  F17 = 92,
  F18 = 93,
  F19 = 94,
  F20 = 95,
  F21 = 96,
  F22 = 97,
  F23 = 98,
  F24 = 99,
  Numpad0 = 100,
  Numpad1 = 101,
  Numpad2 = 102,
  Numpad3 = 103,
  Numpad4 = 104,
  Numpad5 = 105,
  Numpad6 = 106,
  Numpad7 = 107,
  Numpad8 = 108,
  Numpad9 = 109,
  NumpadAdd = 110,
  NumpadSubtract = 111,
  NumpadMultiply = 112,
  NumpadDivide = 113,
  NumpadDecimal = 114,
  NumpadEnter = 115,
  NumpadEqual = 116,
  VolumeUp = 117,
  VolumeDown = 118,
  VolumeMute = 119,
  MediaPlayPause = 120,
  MediaStop = 121,
  MediaNext = 122,
  MediaPrevious = 123,
  BrowserBack = 124,
  BrowserForward = 125,
  BrowserRefresh = 126,
  BrowserStop = 127,
  BrowserSearch = 128,
  BrowserFavorites = 129,
  BrowserHome = 130,
  LaunchMail = 131,
  LaunchApp1 = 132,
  LaunchApp2 = 133,
  IntlBackslash = 134,
  IntlYen = 135,
  IntlRo = 136,
  ContextMenu = 137,
}

/** Mouse button event payload for onMouseDown / onMouseUp / onClick callbacks. */
export interface MouseButtonEventJs {
  x: number
  y: number
  button: ButtonJs
  time: number
}

export interface MouseDataJs {
  x: number
  y: number
  button?: ButtonJs
}

/** Mouse move event payload for onMouseMove callbacks. */
export interface MouseMoveEventJs {
  x: number
  y: number
  time: number
}

export interface RectJs {
  x: number
  y: number
  width: number
  height: number
}

export declare enum ScrollDirectionJs {
  Up = 0,
  Down = 1,
  Left = 2,
  Right = 3,
}

/** Press a key */
export declare function simulateKeyPress(key: KeyJs): void

/** Release a key */
export declare function simulateKeyRelease(key: KeyJs): void

/** Tap a key (press + release) */
export declare function simulateKeyTap(key: KeyJs): void

/** Click a mouse button (press + release) */
export declare function simulateMouseClick(button: ButtonJs): void

/** Move the mouse to absolute coordinates */
export declare function simulateMouseMove(x: number, y: number): void

/** Press a mouse button */
export declare function simulateMousePress(button: ButtonJs): void

/** Release a mouse button */
export declare function simulateMouseRelease(button: ButtonJs): void

/**
 * Start listening for input events with a callback.
 * Returns a HookJs instance that can be used to stop the listener.
 *
 * `event_mask` is an optional bitmask that filters events on the native side before
 * crossing the NAPI boundary. This is a performance optimization — high-frequency
 * events like MouseMoved never reach JS if the corresponding bit is not set.
 *
 * Use the `EVENT_MASK_*` constants to compose masks. If `None`, all events are forwarded.
 * The mask can be updated at runtime via `HookJs.setEventMask()`.
 */
export declare function startListen(callback: (event: EventJs) => void, eventMask?: number | undefined | null): HookJs

export interface SystemSettingsJs {
  keyboardRepeatRate?: number
  keyboardRepeatDelay?: number
  mouseSensitivity?: number
  mouseAcceleration?: number
  mouseAccelerationThreshold?: number
  doubleClickTime?: number
  keyboardLayout?: string
}

export interface WheelDataJs {
  x: number
  y: number
  direction: ScrollDirectionJs
  delta: number
}

/** Wheel event payload for onWheel callbacks. */
export interface WheelEventJs {
  x: number
  y: number
  direction: ScrollDirectionJs
  delta: number
  time: number
}
