/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class HookJs {
  stop(): void
  get isRunning(): boolean
}

export declare const enum ButtonJs {
  Left = 0,
  Right = 1,
  Middle = 2,
  Button4 = 3,
  Button5 = 4,
  Unknown = 5,
}

export interface DisplayInfoJs {
  id: number
  bounds: RectJs
  scaleFactor: number
  refreshRate?: number
  isPrimary: boolean
}

export interface EventJs {
  eventType: EventTypeJs
  time: number
  keyboard?: KeyboardDataJs
  mouse?: MouseDataJs
  wheel?: WheelDataJs
}

export declare const enum EventTypeJs {
  HookEnabled = 0,
  HookDisabled = 1,
  KeyPressed = 2,
  KeyReleased = 3,
  KeyTyped = 4,
  MousePressed = 5,
  MouseReleased = 6,
  MouseClicked = 7,
  MouseMoved = 8,
  MouseDragged = 9,
  MouseWheel = 10,
}

/** Get display at a specific point */
export declare function getDisplayAtPoint(x: number, y: number): DisplayInfoJs | null

/** Get all displays */
export declare function getDisplays(): Array<DisplayInfoJs>

/** Get the current mouse cursor position */
export declare function getMousePosition(): MouseDataJs

/** Get the primary display */
export declare function getPrimaryDisplay(): DisplayInfoJs

/** Get system settings */
export declare function getSystemSettings(): SystemSettingsJs

export interface KeyboardDataJs {
  key: KeyJs
  rawCode: number
}

export declare const enum KeyJs {
  KeyA = 0,
  KeyB = 1,
  KeyC = 2,
  KeyD = 3,
  KeyE = 4,
  KeyF = 5,
  KeyG = 6,
  KeyH = 7,
  KeyI = 8,
  KeyJ = 9,
  KeyK = 10,
  KeyL = 11,
  KeyM = 12,
  KeyN = 13,
  KeyO = 14,
  KeyP = 15,
  KeyQ = 16,
  KeyR = 17,
  KeyS = 18,
  KeyT = 19,
  KeyU = 20,
  KeyV = 21,
  KeyW = 22,
  KeyX = 23,
  KeyY = 24,
  KeyZ = 25,
  Num0 = 26,
  Num1 = 27,
  Num2 = 28,
  Num3 = 29,
  Num4 = 30,
  Num5 = 31,
  Num6 = 32,
  Num7 = 33,
  Num8 = 34,
  Num9 = 35,
  F1 = 36,
  F2 = 37,
  F3 = 38,
  F4 = 39,
  F5 = 40,
  F6 = 41,
  F7 = 42,
  F8 = 43,
  F9 = 44,
  F10 = 45,
  F11 = 46,
  F12 = 47,
  Escape = 48,
  Space = 49,
  Enter = 50,
  Backspace = 51,
  Tab = 52,
  ShiftLeft = 53,
  ShiftRight = 54,
  ControlLeft = 55,
  ControlRight = 56,
  AltLeft = 57,
  AltRight = 58,
  MetaLeft = 59,
  MetaRight = 60,
  CapsLock = 61,
  Delete = 62,
  ArrowLeft = 63,
  ArrowRight = 64,
  ArrowUp = 65,
  ArrowDown = 66,
  Unknown = 67,
}

export interface MouseDataJs {
  x: number
  y: number
  button?: ButtonJs
}

export interface RectJs {
  x: number
  y: number
  width: number
  height: number
}

export declare const enum ScrollDirectionJs {
  Up = 0,
  Down = 1,
  Left = 2,
  Right = 3,
}

/** Press a key */
export declare function simulateKeyPress(key: KeyJs): void

/** Release a key */
export declare function simulateKeyRelease(key: KeyJs): void

/** Tap a key (press + release) */
export declare function simulateKeyTap(key: KeyJs): void

/** Click a mouse button (press + release) */
export declare function simulateMouseClick(button: ButtonJs): void

/** Move the mouse to absolute coordinates */
export declare function simulateMouseMove(x: number, y: number): void

/** Press a mouse button */
export declare function simulateMousePress(button: ButtonJs): void

/** Release a mouse button */
export declare function simulateMouseRelease(button: ButtonJs): void

/**
 * Start listening for input events with a callback.
 * Returns a HookJs instance that can be used to stop the listener.
 */
export declare function startListen(callback: (event: EventJs) => void): HookJs

export interface SystemSettingsJs {
  keyboardRepeatRate?: number
  keyboardRepeatDelay?: number
  mouseSensitivity?: number
  mouseAcceleration?: number
  mouseAccelerationThreshold?: number
  doubleClickTime?: number
  keyboardLayout?: string
}

export interface WheelDataJs {
  x: number
  y: number
  direction: ScrollDirectionJs
  delta: number
}
